[project]
name = "letsbuilda-pypi"
version = "5.0.0"
description = "A wrapper for PyPI's API and RSS feed"
authors = [
    { name = "Bradley Reynolds", email = "bradley.reynolds@darbia.dev" },
]
license = { text = "MIT" }
readme = "README.md"
requires-python = ">=3.11.4"
dependencies = [
    "aiohttp",
    "xmltodict",
    "pendulum",
]

[project.urls]
repository = "https://github.com/letsbuilda/letsbuilda-pypi/"
documentation = "https://docs.letsbuilda.dev/letsbuilda-pypi/"

[project.optional-dependencies]
dev = [
    "pre-commit",
    "black",
    "ruff",
]
tests = [
    "pytest",
]
docs = [
    "sphinx",
    "furo",
    "sphinx-autoapi",
    "releases",
    "toml",
]

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[tool.black]
target-version = ["py311"]
line-length = 120

[tool.ruff]
select = ["ALL"]
target-version = "py311"
line-length = 120

[tool.ruff.pydocstyle]
convention = "numpy"

[tool.pytest.ini_options]
addopts = "tests -r a -v --doctest-modules src"
