name: "Publish Python 🐍 distributions 📦 to PyPI"

on:
  release:
    types: [released]

jobs:
  build-publish:
    name: "Build and publish Python 🐍 distributions 📦 to PyPI"
    runs-on: ubuntu-latest
    permissions:
      id-token: write

    steps:
      - name: "Checkout repository"
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9

      - name: "Set up Python 3.x"
        uses: actions/setup-python@0cbcb9a3d7c0b228a2c4fbde82b6e8855233cd92
        with:
          python-version: "3.x"
          cache: "pip"
          cache-dependency-path: "pyproject.toml"

      - name: "Install pypa/build"
        run: >-
          python -m
          pip install
          build
          --user

      - name: "Build a binary wheel and a source tarball"
        run: >-
          python -m
          build
          --outdir dist/

      - name: "Upload packages"
        uses: actions/upload-artifact@65d862660abb392b8c4a3d1195a2108db131dd05
        with:
          name: packages
          path: dist

      - name: "Publish distribution 📦 to PyPI"
        uses: pypa/gh-action-pypi-publish@a56da0b891b3dc519c7ee3284aff1fad93cc8598
        with:
          skip-existing: true
          verbose: true
          print-hash: true
