name: "Python - Publish to PyPI"

on:
  release:
    types: [released]

jobs:
  publish:
    permissions:
      id-token: write
    uses: darbiadev/.github/.github/workflows/python-pypi-publish.yaml@main
