name: "Python - Publish to PyPI"

on:
  release:
    types: [released]

jobs:
  publish:
    permissions:
      id-token: write
    uses: letsbuilda/.github/.github/workflows/python-pypi-publish.yaml@486f136e171228dd8d8820facba6c9bcd0e76a13
